/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ucr.proyecto.gui;

import com.ucr.proyecto.domain.Client;
import com.ucr.proyecto.domain.Empleado;
import com.ucr.proyecto.domain.Transaccion;
import com.ucr.proyecto.util.Constantes;

/**
 *
 * @author Juan Carlos Mora B44540
 */
public class Retiro extends javax.swing.JPanel {

    /**
     * Creates new form Retiro
     */
    Empleado emp;
    PanelDeControl p;
    public Retiro(Empleado empAct, PanelDeControl p) {
        initComponents();
        this.emp = empAct;
        this.p = p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jb_retirar = new javax.swing.JButton();
        jtf_monto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jl_cuenta = new javax.swing.JLabel();
        jtf_Detalle = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        jb_retirar.setText("Retirar");
        jb_retirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_retirarActionPerformed(evt);
            }
        });

        jtf_monto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_montoActionPerformed(evt);
            }
        });

        jLabel1.setText("Ingrese el monto a debitar");

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jl_cuenta.setText("Cuenta Num:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jl_cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_cuenta)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jtf_Detalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_DetalleActionPerformed(evt);
            }
        });

        jLabel2.setText("Ingrese el detalle");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtf_Detalle, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_monto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb_retirar)
                        .addGap(53, 53, 53))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(262, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtf_Detalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_retirar)
                    .addComponent(jtf_monto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_montoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_montoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_montoActionPerformed

    private void jtf_DetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_DetalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_DetalleActionPerformed

    private void jb_retirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_retirarActionPerformed
        // TODO add your handling code here
        if (jtf_monto.getText().equals("")) return;
        double monto = Double.parseDouble(jtf_monto.getText());
        Transaccion t = new Transaccion(emp,
                monto,
                "debitar", Constantes.empleadoNulo, jtf_Detalle.getText());
        
        new Client(5700, Constantes.ENVIAR_TRANSACCION_DEBITAR, t).start();
        if(p.getMonto() >= monto) p.actualizaMonto(p.getMonto()-monto);
        
        jtf_Detalle.setText("");
        jtf_monto.setText("");
    }//GEN-LAST:event_jb_retirarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jb_retirar;
    private javax.swing.JLabel jl_cuenta;
    private javax.swing.JTextField jtf_Detalle;
    private javax.swing.JTextField jtf_monto;
    // End of variables declaration//GEN-END:variables
}
